### ISSUE TITLE
Add place for acknowledgements 

### ISSUE THREAD

**Issue by lukefretwell** [GetDKAN/ops#51] opened 2017-10-23 22:57 UTC

**Comment by marctjones** [comment] 2017-10-24 17:59
Is this a duplicate of this: https://github.com/GetDKAN/dkan/issues/2169

**Comment by lukefretwell** [comment] 2017-10-24 18:25
@marctjones is the file in the repo? Other places we should include or reference, like an acknowledgements page in docs?

**Comment by marctjones** [comment] 2017-10-24 18:57
I usually recommend putting extensive acknowledgements in a file in the code base.

We might also want to consider putting an acknowledgements page in the web app itself that is a little more curated but highlights specific contributors with a link back to the more complete acknowledgements file. 

Also good to consider as a location to include any required statements that contracts might require. Such as saying it is funded by such and such federal agency, but is not a endorsement. 

I think that is totally different then the getdkan.org website, where the companies listed on that we probably want to restrict to ourselves and other companies that we have a partnership with.

**Comment by kimwdavidson** [comment] 2018-01-16 20:23
Duplicate. Closing.

**Closed by kimwdavidson** 2018-01-16 20:23 UTC
Labels: community
